### PR TITLE
Finished lesson filters #193

### PR DESCRIPTION
**Pull request by amandavisconti**
My work was built on code from the PH/jekyll repo as it stood late last summer, so most of the differences are correct in Fred's version rather than mine. 

I did make a few relevant changes beyond lessons.md and topics.yml. In particular, I should check that any new/updated lessons since summer get the new front matter structure/content.

### CODE REVIEW

**Comment by mdlincoln** [comment]
This seems like an unholy number of line changes - does this build correctly on your machine, @amandavisconti ?

**Comment by amandavisconti** [comment]
@mdlincoln Eek, yes. I'll check this over and resubmit. I tried using a diff GUI locally to pull out just the changes we wanted to keep, but looks like that first try didn't work so well!

**Comment by mdlincoln** [comment]
I wonder if maybe it tried to diff every single object (including images!) rather than just the lesson page & template pages that have the substantive changes?

**Comment by amandavisconti** [comment]
I did some manual cleanup, and there's now a much more modest amount of line changes...

**Comment by mdlincoln** [comment]
I'm still seeing a huge number of line changes included in the entire PR, probably because it still contains those previous messy commits. Is it possible to open a fresh PR with _only_ the correct changes?

**Comment by amandavisconti** [comment]
@mdlincoln Yes! Will do right now. Thanks for assisting with managing the messiness.

**Comment by amandavisconti** [comment]
Taking longer than expected due to SSH key setup on new work computer, but doing a new pull request is on my to-do list for today or tomorrow.

**Comment by amandavisconti** [comment]
Haven't fixed the SSH key issue, but I think I can just push from my home computer tonight. Sorry for the delay.

**Pull request closed without merging**
