### PR TITLE
Cleaned up commit for #193 lesson filter work

### PR DESCRIPTION
**Pull request by amandavisconti**
Just selected the changed files (lessons.md, _config.yml, /lessons folder, _includes/lesson_describe.html, maybe list.min.js?) and confirmed it works locally (possible I made a few other changes to other files, but I'll check that separately since they'd just be textual edits and not code). @mdlincoln @fredgibbs Thanks!

### CODE REVIEW

**Comment by mdlincoln** [comment]
This appears to delete all the files in `_lessons`??

**Comment by mdlincoln** [comment]
OK, part of the reason that this still registers as deleting a huge number of files is because your commit would remove the `_lessons` directory in favor of a `lessons` directory. 

Can either of you bring me up to speed on the decision made about using `_lessons` vs. `lessons`?

**Comment by amandavisconti** [comment]
The _config.yml now applies `lesson: true` to anything in /lessons—we ended up keeping the location of /lessons the same as it always has been in programminghistorian/jekyll. 

I'd originally changed things to /_lessons because I was confused about what file types could be filtered/sorted the way I wanted to (I think I had categories and collections confused?). But there's no need for this, so I reverted to /lessons.

**Comment by amandavisconti** [comment]
I remember: I [read](https://stackoverflow.com/questions/9110803/make-custom-page-based-loop-in-jekyll/9117390#9117390) that _site only knows about pages, posts, and categories; knew I wanted to call {{ site.x }}; and thought lessons didn't count as pages.

**Comment by mdlincoln** [comment]
OK, so then it would actually be _correct_ to remove the `_lessons` dir from @fredgibbs repo with this PR.

**Comment by amandavisconti** [comment]
@mdlincoln Correct. Will check this when I'm home again.

**Comment by fredgibbs** [comment]
After working through lots of git messages i've never seen before, i've merged all the changes from this PR successfully (but not committed them back to GitHub, so the PR is still open). A few files i've been editing seem to have gotten borked in our competing commit frenzies of late, but i have pre-merge versions that i can use to restore some layout work and still keep @amandavisconti's latest lesson edits and code work. (There's probably a more official git way to do that [and to manage our concurrent forks generally], but this is way outside my git experience.) I should have everything up and running tomorrow morning for live preview and we can double check that i didn't mess things up too badly. Thanks @mdlincoln and @amandavisconti!

**Comment by amandavisconti** [comment]
Thanks @fredgibbs and @mdlincoln! Sorry the merge was so messy.

**Comment by fredgibbs** [comment]
wasn't messy at all! all latest functionality (minus some ongoing display/formatting issues) should be working well on preview site now.

**Comment by mdlincoln** [comment]
Brilliant 😀

**Pull request merged**
